layout_spectrum: 0.028744873590767384
typography_spectrum: 0.3137219075579196
color:
  brandStrength: 0.3921900235582143
  lightness: 0.11689334618858993
  saturation: 0.49620592780411243
  rhythmicContrast: 0.5282872673124075
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Web y estrategia
